### ISSUE TITLE
Julia 1.0 libjulia.dll not found

### ISSUE THREAD

**Issue by danmrc** [Non-Contradiction/JuliaCall#67] opened 2018-08-31 01:01 UTC
Hi,

I recently downloaded Julia 1.0 and decided to use JuliaCall with it - as I did with Julia 0.6.4. However, when I use the julia_setup(path), it throws the following:

```
Julia version 1.0.0 at location C:\Users\danmc\AppData\Local\JULIA-~1.0\bin will be used.
Error in juliacall_initialize(.julia$dll_file) : 
  C:\Users\danmc\AppData\Local\JULIA-~1.0\bin\libjulia.dll - unable to find the specified module 
```
(I translated the error message because it was in my native language) 

However, the .dll is there and I am able to run Julia from atom. Here is the info from R: 

```
Session info ------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, mingw32             
 ui       RStudio (1.1.453)           
 language (EN)                        
 collate  Portuguese_Brazil.1252      
 tz       America/Sao_Paulo           
 date     2018-08-30                  

Packages ----------------------------------------------------------------------------------------------
 package    * version     date       source                                      
 backports    1.1.2       2017-12-13 CRAN (R 3.5.0)                              
 base       * 3.5.1       2018-07-02 local                                       
 blogdown     0.8         2018-07-15 CRAN (R 3.5.1)                              
 bookdown     0.7         2018-02-18 CRAN (R 3.5.1)                              
 compiler     3.5.1       2018-07-02 local                                       
 datasets   * 3.5.1       2018-07-02 local                                       
 devtools     1.13.6      2018-06-27 CRAN (R 3.5.1)                              
 digest       0.6.16      2018-08-22 CRAN (R 3.5.1)                              
 evaluate     0.11        2018-07-17 CRAN (R 3.5.1)                              
 graphics   * 3.5.1       2018-07-02 local                                       
 grDevices  * 3.5.1       2018-07-02 local                                       
 htmltools    0.3.6       2017-04-28 CRAN (R 3.5.1)                              
 httpuv       1.4.5       2018-07-19 CRAN (R 3.5.1)                              
 JuliaCall    0.16.0.9000 2018-08-30 Github (Non-Contradiction/JuliaCall@32da446)
 knitr        1.20        2018-02-20 CRAN (R 3.5.1)                              
 later        0.7.3       2018-06-08 CRAN (R 3.5.1)                              
 magrittr     1.5         2014-11-22 CRAN (R 3.5.1)                              
 memoise      1.1.0       2017-04-21 CRAN (R 3.5.1)                              
 methods    * 3.5.1       2018-07-02 local                                       
 mime         0.5         2016-07-07 CRAN (R 3.5.0)                              
 promises     1.0.1       2018-04-13 CRAN (R 3.5.1)                              
 R6           2.2.2       2017-06-17 CRAN (R 3.5.1)                              
 Rcpp         0.12.18     2018-07-23 CRAN (R 3.5.1)                              
 rmarkdown    1.10        2018-06-11 CRAN (R 3.5.1)                              
 rprojroot    1.3-2       2018-01-03 CRAN (R 3.5.1)                              
 rstudioapi   0.7         2017-09-07 CRAN (R 3.5.1)                              
 servr        0.10        2018-05-30 CRAN (R 3.5.1)                              
 stats      * 3.5.1       2018-07-02 local                                       
 stringi      1.1.7       2018-03-12 CRAN (R 3.5.0)                              
 stringr      1.3.1       2018-05-10 CRAN (R 3.5.1)                              
 tools        3.5.1       2018-07-02 local                                       
 utils      * 3.5.1       2018-07-02 local                                       
 withr        2.1.2       2018-03-15 CRAN (R 3.5.1)                              
 xfun         0.3         2018-07-06 CRAN (R 3.5.1)                              
 yaml         2.2.0       2018-07-25 CRAN (R 3.5.1)  
```

Btw, I tried both the CRAN and the github version of JuliaCall. They both throw the same error.  

Thanks in advance

**Comment by Non-Contradiction** [comment] 2018-08-31 01:14
Thank you for providing feedback.
Does adding ` C:\Users\danmc\AppData\Local\JULIA-~1.0\bin` to PATH work?

**Comment by danmrc** [comment] 2018-08-31 01:37
Sorry, I wasn’t clear. I am calling the julia_setup with `C:/Users/danmc/AppData/Local/Julia-1.0/bin` (which is the same path, I tried copying each one and they get to the same place). If I change it, it throws another error, that it didn’t find Julia (that makes sense). I have also tried setting the path using `options(JULIA_HOME = ”c:/Users/danmc/AppData/Local/Julia-1.0/bin”)`

**Comment by Non-Contradiction** [comment] 2018-08-31 02:04
There might be problems with other julia dlls beyond `C:/Users/danmc/AppData/Local/Julia-1.0/bin/libjulia.dll`. What are the dlls in `C:/Users/danmc/AppData/Local/Julia-1.0/bin`? There should be more than just `libjulia.dll`.

How about adding `C:/Users/danmc/AppData/Local/Julia-1.0/bin` to the PATH variable in the windows system? Like doing `set PATH=C:/Users/danmc/AppData/Local/Julia-1.0/bin;%PATH%` or edit PATH variable in the system setting.
After setting the system's path variable, then `julia_setup()` should be able to find julia without `JULIA_HOME` argument in a *fresh* RStudio session, and if the error goes away, then it means that the problem might be locating the other dlls needed by julia beyond `libjulia.dll`.

**Comment by danmrc** [comment] 2018-09-06 14:37
Here is the list of files in the `C:/Users/danmc/AppData/Local/Julia-1.0/bin`:

- 7z.dll
- 7z.exe
- BugpointPasses.dll
- busybox.exe
- julia.exe
- libamd.dll
- libatomic-1.dll
- libcamd.dll
- libccalltest.dll
- libccolamd.dll
- libcholmod.dll
- libcolamd.dll
- libdSFMT.dll
- libexpat-1.dll
- libgcc_s_seh-1.dll
- libgfortran-3.dll
- libgit2.dll
- libgmp.dll
- libjulia-debug.dll
- libjulia.dll
- libmbedcrypto.dll
- libmbedtls.dll
- libmbedx509.dll
- libmpfr.dll
- libopenblas64_.dll
- libopenlibm.dll
- libpcre2-8.dll
- libpcre2-posix.dll
- libquadmath-0.dll
- libspqr.dll
- libssh2.dll
- libssp-0.dll
- libstdc++-6.dll
- libsuitesparse_wrapper.dll
- libsuitesparseconfig.dll
- libumfpack.dll
- libuv-2.dll
- libwinpthread-1.dll
- LLVM.dll
- LLVMHello.dll
- zlib1.dll

I tried setting the path as you said and it throws an error "Julia is not found". I have changed both the system and the user path. And I have restarted the R Studio.

**Comment by Non-Contradiction** [comment] 2018-09-06 16:49
It's really strange to have "Julia is not found" error after setting PATH.
How about doing `setwd("C:/Users/danmc/AppData/Local/Julia-1.0/bin")` before `julia_setup(JULIA_HOME = "C:/Users/danmc/AppData/Local/Julia-1.0/bin")`? 
This is automatically done by previous `JuliaCall` version, but removed because of some reports of segfaults.

**Comment by danmrc** [comment] 2018-09-06 18:11
I might have done the path wrong. I followed this tutorial (https://www.computerhope.com/issues/ch000549.htm)

And setting the wd in the `C:/Users/danmc/AppData/Local/Julia-1.0/bin` throws a "R Session Aborted"

**Comment by Non-Contradiction** [comment] 2018-09-06 18:20
The tutorial is fine. It should work.
So how about setting PATH variable and then just type `julia` in command line, no results?
If `julia` can be found from the command line, then it should be fine for `JuliaCall` to find `julia` too.

Yeah.. `setwd` seems like a bad idea, but the segfault actually implies that `JuliaCall` is able to find "libjulia.dll" and to try to load it, otherwise the segfault is not going to happen...

**Comment by Non-Contradiction** [comment] 2018-09-06 18:37
How about run R as administrator? I searched through Google, and there are some people mentioning this. But I'm not sure whether it is going to work....

**Comment by danmrc** [comment] 2018-09-06 18:58
First of all, thanks for the help. 

And setting the path to Julia 1.0.0 in the path makes Julia work through the prompt. But using `julia_setup()` just makes the R session be aborted - although I am back to my original wd. 

I have tried running R as an administrator and the same things happened - when the path is set, it just crashes and using the `julia_setup(C:/Users/danmc/AppData/Local/Julia-1.0/bin)` it does not find the dll.

**Comment by Non-Contradiction** [comment] 2018-09-06 20:36
I guess the problem is that some dlls from julia doesn't play well with R.
We may need to add R dlls path to PATH in front of the path for julia,
so that R finds the correct dlls first, and then if julia is looking for additional dlls, it can look into the julia folder.

BTW, do you have Rtools from CRAN installed?

**Comment by danmrc** [comment] 2018-09-07 14:37
Yes, I have the Rtools.

**Comment by Non-Contradiction** [comment] 2018-09-07 14:53
Then it's better to check whether Rtools paths are in the PATH variable of windows system,
note that we need both Rtools path and Rtools gcc path, and they need to be before julia's path to make sure R doesn't pick up julia's dlls.
For example, in the [appveyor.yml](https://github.com/Non-Contradiction/JuliaCall/blob/master/appveyor.yml) which setups `JuliaCall` for testing on appveyor windows, we have the following: 
https://github.com/Non-Contradiction/JuliaCall/blob/32da4468bb2612eab7ac67135ddc8f31ce71e9f4/appveyor.yml#L61
And the Rtools paths are before R's path which is before julia's path.

**Comment by danmrc** [comment] 2018-09-07 21:38
Are you sure you mean `c:\Rtools\gcc-4.6.3\bin`? Because I don't have such a folder. I have a `mingw_64`

**Comment by Non-Contradiction** [comment] 2018-09-07 21:45
Maybe something has changed, I can't find any documentation about `c:\Rtools\gcc-4.6.3\bin` now.
Maybe just `c:\Rtools\bin` is okay. 
What is the content of `c:\Rtools\bin`?

**Comment by danmrc** [comment] 2018-09-07 21:49
There you go:

- aspell.exe
- basename.exe
- cat.exe
- cmp.exe
- comm.exe
- cp.exe
- cut.exe
- cygpath.exe
- date.exe
- diff.exe
- dirname.exe
- du.exe
- echo.exe
- egrep
- expr.exe
- file.exe
- find.exe
- gawk.exe
- grep.exe
- gzip.exe
- head.exe
- ln.exe
- ls.exe
- make.exe
- md5sum.exe
- mkdir.exe
- msys-2.0.dll
- msys-bz2-1.dll
- msys-gcc_s-1.dll
- msys-gmp-10.dll
- msys-iconv-2.dll
- msys-intl-8.dll
- msys-magic-1.dll
- msys-mpfr-6.dll
- msys-ncursesw6.dll
- msys-pcre-1.dll
- msys-readline7.dll
- msys-z.dll
- mv.exe
- objdump.exe
- od.exe
- patch.exe
- pedump.exe
- qpdf.exe
- qpdf21.dll
- rm.exe
- rmdir.exe
- rsync.exe
- sed.exe
- sh.exe
- sort.exe
- tar.exe
- texindex.exe
- touch.exe
- tr.exe
- uname.exe
- uniq.exe
- unzip.exe
- wc.exe
- zip.exe

**Comment by Non-Contradiction** [comment] 2018-09-12 14:42
Does adding Rtools path before julia path in the system PATH variable help?

**Comment by adrianadermon** [comment] 2018-09-18 14:50
I have the same problem, on two different computers running Windows 10. 

When I run `julia_setup()` in R, I get a popup from Rterm.exe saying 

    The procedure entry point _Zst14__once_functor could not be located in the dynamic link library C:\Users\adria\AppData\Local\Julia-1.0.0\bin\LLVM.dll.

I also get the following error in the R prompt

    Julia version 1.0.0 at location C:\Users\adria\AppData\Local\JULIA-~1.0\bin will be used.
    Error in juliacall_initialize(.julia$dll_file) :
      C:\Users\adria\AppData\Local\JULIA-~1.0\bin\libjulia.dll - The specified procedure could not be found.

I have tried all the remedies suggested above, and nothing helps.

**Comment by Non-Contradiction** [comment] 2018-09-18 16:35
@adrianadermon It seems like a problem with missing DLL. The _Zst14_once_functor symbol seems to be a libstdc++ one. But the julia should already have the libstdc++ version it needs. And the path should already be in the PATH, which is searchable when loading DLL... And the DLLs needed by R are also in Rtools folder, which is also in PATH... So I currently really don't know what is the root of this problem, and I'll try to get a Windows machine to test it myself. 

There are currently several things to try, but they may not have any effect....
1. Put the Rtools path behind the Julia path in PATH, and these two paths should be in front of any other folders in PATH;
2. Or we can just delete the Rtools path? The CRAN version of JuliaCall shouldn't need to compile, so actually no need for Rtools.
3. What's the version of Rtools? Rtools 34 and Rtools 35 should all be good for R 3.5.x. So maybe we can try different versions of Rtools?

**Comment by adrianadermon** [comment] 2018-09-19 13:45
Moving the Julia path to the top solved the problem! I did run into another problem, but that's for another issue...

**Comment by Non-Contradiction** [comment] 2018-09-19 14:12
@adrianadermon Thank you for the feedback. Then the problem seems to be that when R loads Julia DLL, it picks up R's C DLL instead of Julia's mistakenly... And putting Julia's DLL path first solves the issue. And feel free to open another issue if you have other problems.
@danmrc Does this also work for you?

**Comment by danmrc** [comment] 2018-09-20 14:36
> Put the Rtools path behind the Julia path in PATH, and these two paths should be in front of any other folders in PATH;

It just crashes the R Session. I have tried changing the order too, with the same effect

> Or we can just delete the Rtools path? The CRAN version of JuliaCall shouldn't need to compile, so actually no need for Rtools.

It just crashes the R Session.

> What's the version of Rtools? Rtools 34 and Rtools 35 should all be good for R 3.5.x. So maybe we can try different versions of Rtools?

35. I had to follow this(https://community.rstudio.com/t/rtools-not-recognized-r3-5-1-rtools-3-5/11311) to make dev_tools accept the R Tools, though.

**Comment by Non-Contradiction** [comment] 2018-09-25 16:48
It seems the Rtools really make the issue more complicated.  The CRAN provides the compiled binary of JuliaCall, which should work without Rtools. So how about temporarily removing all the `setenv` things needed by Rtools, and also temporarily remove the Rtools folders from PATH variable of the system, and just installing JuliaCall from CRAN?

**Comment by virgodi** [comment] 2018-10-23 13:10
Hi @danmrc, did you manage to find a solution ? I'm experiencing the exact same issue...

**Comment by Non-Contradiction** [comment] 2018-10-23 14:21
@virgodi Did you try to add the folder of Julia binary to PATH or set up the current folder by `setwd`? PS: there is a problem in running JuliaCall from RStudio or other R IDE on windows currently, but it should be okay to run from command line.

**Comment by virgodi** [comment] 2018-10-23 14:46
Hi ! Setting the path to the folder made Rstudio Crash. 

I'll try through command line, thanks ! Any plans on fixing the Rstudio issue ?

Much appreciated !

V

**Comment by Non-Contradiction** [comment] 2018-10-23 15:33
@virgodi The RStudio issue is actually caused by Julia itself, and there is nothing that can be done at JuliaCall side to fix it, see https://github.com/JuliaLang/julia/issues/28820, but it seems that the problem has already been fixed on Julia github master. Although the fix is not in the released version yet, it hopefully will be included in Julia 1.0.2 patch release.

**Comment by virgodi** [comment] 2018-10-25 14:29
Understood, thank you for clarifying !

**Comment by Non-Contradiction** [comment] 2018-12-13 21:41
@danmrc Thank you for the feedback! There's no need for apologies.

**Closed by Non-Contradiction** 2018-12-13 21:41 UTC
Labels: Windows
