### ISSUE TITLE
julia_setup() hanging after message on "Loading setup script"

### ISSUE THREAD

**Issue by dmbates** [Non-Contradiction/JuliaCall#34] opened 2018-03-21 20:17 UTC
I haven't work out what is triggering this but I sometimes have R hang after a call to `julia_setup`.  It looks like
```r
> library(JuliaCall)      
> j <- julia_setup()      
Julia version 0.6.2 at location /usr/local/src/julia-d386e40c17/bin will be used.                        
Julia initiation...       
Finish Julia initiation.  
Loading setup script for JuliaCall... 
Segmentation fault (core dumped)
```
The last line was printed after a very long wait (like hours).

Some of the time I avoid the segfault in the REPL.  Inside RStudio I almost always segfault.

This is on an Ubuntu 17.10 64-bit system with `R version 3.4.4 (2018-03-15) -- "Someone to Lean On" ` and official download of Julia v0.6.2

I know this isn't much to go on.  Please let me know if I can do some further exploration.

**Comment by Non-Contradiction** [comment] 2018-03-21 20:35
Thanks for the feedback!

The problem on Rcpp I think is a conflict between some of the library used by Julia and RStudio, mainly about c and cpp.

It is better to load `JuliaCall` before other `R` packages which uses `Rcpp` to avoid segfaults.

And it may be helpful to look at the setting of CI on ubuntu, which can be found at <https://github.com/Non-Contradiction/JuliaCall/blob/master/.travis.yml>.
Setting LD_LIBRARY_PATH may be of help, like `export R_LD_LIBRARY_PATH="$(R RHOME)/lib:$HOME/julia/lib/julia";`.

What is the result of cloning `JuliaCall` repo and do `R CMD check`?

**Comment by dmbates** [comment] 2018-03-21 21:06
I used RStudio with the `JuliaCall.Rrog` file from the repository.  Running `R CMD check` through `devtools::check` worked okay.
```sh
==> devtools::check(document = FALSE)

Setting env vars --------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building JuliaCall ------------------------------------------------------------
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD build '/home/bates/git/JuliaCall' --no-resave-data --no-manual 

* checking for file ‘/home/bates/git/JuliaCall/DESCRIPTION’ ... OK
* preparing ‘JuliaCall’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘JuliaCall_0.12.1.9000.tar.gz’

Setting env vars --------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_USE_ASPELL_: TRUE
_R_CHECK_CRAN_INCOMING_           : FALSE
_R_CHECK_FORCE_SUGGESTS_          : FALSE
Checking JuliaCall ------------------------------------------------------------
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD check '/tmp/RtmpvjhaFy/JuliaCall_0.12.1.9000.tar.gz' --as-cran  \
  --timings --no-manual 

* using log directory ‘/home/bates/git/JuliaCall.Rcheck’
* using R version 3.4.4 (2018-03-15)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘JuliaCall/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘JuliaCall’ version ‘0.12.1.9000’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘JuliaCall’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’ OK
* checking for unstated dependencies in vignettes ... [39s/38s]
 OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... OK
* DONE
Status: OK



R CMD check results
0 errors | 0 warnings | 0 notes

R CMD check succeeded
```
I think used the "Install and restart" button which loaded the package but I still got a segfault when trying to run `julia_setup()` in Rstudio.  In the REPL `julia_setup()` did work.

**Comment by randy3k** [comment] 2018-03-21 21:52
I also got an issue to use [rtichoke](https://github.com/randy3k/rtichoke), not sure if it is related and I remember it was working fine for the previous version of JuliaCall.

```
                                                                          raceb:
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/deps/promp2
    result = yield f
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/deps/prompt
    new_f = coroutine.send(None)
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/deps/prompc
    self.reset()
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/deps/prompt
    self.renderer.reset()
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/deps/prompt
    self.output.flush()
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/deps/promph
    self.stdout.flush()
BlockingIOError: [Errno 35] write could not complete without blocking

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/rtichokeapt
    text = mp.run()
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/modalprompn
    return self.app.run(inputhook=self.inputhook)
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/deps/prompn
    return run()
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/deps/prompn
    return f.result()
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/deps/prompt
    raise self._exception
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/deps/prompt
    new_f = coroutine.throw(exc)
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/deps/promp2
    assert not self._is_running
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/callbacks.e
    unexpected error was caught.ODING), add_history)
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/rtichokeapt
r$>

**Comment by Non-Contradiction** [comment] 2018-03-22 00:11
@dmbates Could you try the code in this gist <https://gist.github.com/Non-Contradiction/67a2b740706e7e7697504a7997707fa5> without `julia_setup()` in a fresh R session and see if the segfault persists?

**Comment by Non-Contradiction** [comment] 2018-03-22 00:42
@randy3k This problem is not the same problem and I can reproduce it on my mac. I make some testing but still couldn't locate the cause for this problem.

**Comment by dmbates** [comment] 2018-03-22 16:14
Running in an RStudio console I consistently get segfaults from `julia_setup()`.  Running the explicit calls you suggested did not segfault.
```r
> library(JuliaCall)
> dll_file <- system("julia -e \'print(Libdl.dlpath(\"libjulia\"))\'", intern = TRUE)
> dll_file
[1] "/usr/local/src/julia-d386e40c17/bin/../lib/libjulia.so.0.6"
> JuliaCall:::juliacall_initialize(dll_file)
[1] TRUE
> JuliaCall:::juliacall_cmd('print("1\n")')
1
[1] TRUE
```

Do you want me to step through the `julia_setup` function to see if I can isolate where the segfault occurs?

**Comment by Non-Contradiction** [comment] 2018-03-22 16:56
@dmbates The fact that the code in the gist doesn't segfault is inspiring. Yes, step through `julia_setup` would be helpful. Or you can wait me to write a gist for the essential steps of JuliaCall setup. And we can see which step causes the segfault.

Thanks very much! I don't have access to ubuntu, and travis CI doesn't give helpful information on running code on RStudio. Although I made some attempts like <https://github.com/Non-Contradiction/TestWithRStudio>, but they are not successful.

**Comment by dmbates** [comment] 2018-03-22 17:03
Okay, I will wait for you to distill the relevant calls from the `julia_setup` function.

I have just encountered another problem with somehow looks as if the wrong name for the Julia executable is being used.  I use two different versions of Julia v0.6.2, one compiled with OpenBLAS and one with MKL.  This means that packages need to be recompiled if they were last used on the other version.  If it is a `using` statement through `JuliaCall` that triggers the recompilation, the wrong name for the executable is used.  It ends in `lib/julia` not `bin/julia`
```r
> library(JuliaCall)
> j <- julia_setup()
Julia version 0.6.2 at location /usr/local/src/julia-d386e40c17/bin will be used.
Julia initiation...
Finish Julia initiation.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.
> j$eval("using MixedModels")
INFO: Precompiling module BlockArrays.
Error: Error happens in Julia.
could not spawn `/usr/local/src/julia-d386e40c17/lib/julia -Cx86-64 -J/usr/local/src/julia-d386e40c17/lib/julia/sys.so --compile=yes --depwarn=yes -O0 --output-ji /home/bates/.julia/lib/v0.6/BlockArrays.ji --output-incremental=yes --startup-file=no --history-file=no --color=no --eval 'while !eof(STDIN)
    eval(Main, deserialize(STDIN))
end
'`: permission denied (EACCES)
Stacktrace:
 [1] _jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::Base.PipeEndpoint, ::Base.TTY, ::Base.TTY) at ./process.jl:360
 [2] #374 at ./process.jl:512 [inlined]
 [3] setup_stdio(::Base.##374#375{Cmd}, ::Tuple{Pipe,Base.TTY,Base.TTY}) at ./process.jl:499
 [4] #spawn#373(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{Pipe,Base.TTY,Base.TTY}) at ./process.jl:511
 [5] (::Base.#kw##spawn)(::Array{Any,1}, ::Base.#spawn, ::Cmd, ::Tuple{Pipe,Base.TTY,Base.TTY}) at ./<missing>:0
 [6] #spawn#370(::Nullable{Base.ProcessChain}, ::Function, ::Base.CmdRedirect, 
> 
```

**Comment by Non-Contradiction** [comment] 2018-03-22 17:13
@dmbates This new problem is an issue of julia v0.6, see <https://github.com/JuliaLang/julia/issues/14577>. It has been fixed on master, but currently JuliaCall can't be used on v0.7 yet. 
To patch this problem, JuliaCall provides a function called `julia_library`, so `julia_library("MixedModels")` can be used, it calls julia directly not from the embedding interface to precompile the package, but sometimes even `julia_library` can have problems.

**Comment by Non-Contradiction** [comment] 2018-03-22 18:20
@dmbates I have some theory on the segfault, but I'm not sure. Would you try the code in this gist: <https://gist.github.com/Non-Contradiction/6bd7ffcf9eb4676d5994507db21beea3>
It's basically the setup code where the segfault happens without some REPL and display things.

**Comment by dmbates** [comment] 2018-03-22 18:34
In RStudio the script segfaulted at
```r
JuliaCall:::juliacall_cmd("using RCall")
```

This is using the CRAN version of `JuliaCall`.  Do you want me to install the github master and try again?

**Comment by dmbates** [comment] 2018-03-22 18:36
The cmd did produce one line of output
```
R is already initialized
```

**Comment by Non-Contradiction** [comment] 2018-03-22 18:40
The CRAN version is okay. The github master doesn't have difference in this.

**Comment by Non-Contradiction** [comment] 2018-03-23 18:15
@dmbates I setup a virtual machine with ubuntu,  installed everything needed on it. And I confirmed that the segfault in RStudio+JuliaCall is caused by "using RCall".  `RCall` currently is a dependency of `JuliaCall`. I will try to dig into the `RCall` to see what causes the problem. 
@randy3k Excuse me, do you have any idea about this problem?

**Comment by dmbates** [comment] 2018-03-23 18:18
Thank you for your efforts looking into this.

**Comment by randy3k** [comment] 2018-03-23 20:56
@Non-Contradiction 
I can also reproduct it on RStudio@Ubuntu. RStudio@macOS and terminal R@Ubuntu works fine. Therefore, it is an issue of the combination of RStudio and Ubuntu. Deduced from the error message `R is already initialized`, I beleive it has something to do with [the initialization check](https://github.com/JuliaInterop/RCall.jl/blob/master/src/setup.jl#L151) in RCall. 

```
library(JuliaCall)
dll_file <- system("julia -e \'print(Libdl.dlpath(\"libjulia\"))\'", intern = TRUE)
JuliaCall:::juliacall_initialize(dll_file)
JuliaCall:::juliacall_cmd('const libR = Libdl.dlpath("libR")')
JuliaCall:::juliacall_cmd('println(unsafe_load(cglobal((:R_NilValue, libR),Ptr{Void})))')
```

The same code returns non-empty address on my Mac and terminal@ubuntu, but an empty address on RStudio@Ubuntu.

**Comment by randy3k** [comment] 2018-03-23 21:12
The [fix](https://github.com/JuliaInterop/RCall.jl/commit/43693cbf6287203d1f7ed143347c09918bcb3894) is easier than I thought.
```
> library(JuliaCall)
> dll_file <- system("julia -e \'print(Libdl.dlpath(\"libjulia\"))\'", intern = TRUE)
> JuliaCall:::juliacall_initialize(dll_file)
[1] TRUE
> JuliaCall:::juliacall_cmd('print("using RCall")')
using RCall[1] TRUE
```
But I sill see a segfault when doing `julia_setup()`

**Comment by Non-Contradiction** [comment] 2018-03-23 23:34
@randy3k Thanks for the fix. I find the use the macro of `R""` will cause segfault. For example,
```
library(JuliaCall)
dll_file <- system("julia -e \'print(Libdl.dlpath(\"libjulia\"))\'", intern = TRUE)
JuliaCall:::juliacall_initialize(dll_file)
JuliaCall:::juliacall_cmd('using RCall')
JuliaCall:::juliacall_cmd('RObject(1.0)')
```
 works fine, but
`JuliaCall:::juliacall_cmd('R"1"')` 
will cause segfault.

**Comment by randy3k** [comment] 2018-03-24 00:13
Thanks for narrowing it down. I am on mobile now. Could you try `RCall.render("1")`

**Comment by Non-Contradiction** [comment] 2018-03-24 00:30
`RCall.render("1")` works fine.

**Comment by randy3k** [comment] 2018-03-24 00:52
I have no clues at this point...let me work on it when I get back home

**Comment by randy3k** [comment] 2018-03-24 03:13
I would narrow it down to 
```
library(JuliaCall)
dll_file <- system("julia -e \'print(Libdl.dlpath(\"libjulia\"))\'", intern = TRUE)
JuliaCall:::juliacall_initialize(dll_file)
JuliaCall:::juliacall_cmd('using RCall')
JuliaCall:::juliacall_cmd('const libR = Libdl.dlpath("libR")')

JuliaCall:::juliacall_cmd('ccall((:R_ParseVector,libR), Ptr{RCall.UnknownSxp}, (Ptr{StrSxp},Cint,Ptr{Cint},Ptr{RCall.UnknownSxp}), RObject("1").p, -1, Ref{Cint}(), RCall.sexp(RCall.Const.NilValue))')
```
However, I have zero cules why `R_ParseVector` creates segfault.

**Comment by randy3k** [comment] 2018-03-24 03:40
I finally found it. The same reason as early, for some reasons, `R_NilValue` cannot be resolved and `RCall.Const.NilValue` is not properly loaded.
```
JuliaCall:::juliacall_cmd('print(RCall.Const.NilValue')
```

**Comment by Non-Contradiction** [comment] 2018-03-24 14:34
I haven't figured it out why.
But I see something like
```
JuliaCall:::juliacall_cmd('println(unsafe_load(cglobal((:R_NilValue),Ptr{Void})))')
```
is not an empty address. But
```
JuliaCall:::juliacall_cmd('const libR = Libdl.dlpath("libR")')
JuliaCall:::juliacall_cmd('println(unsafe_load(cglobal((:R_NilValue, libR),Ptr{Void})))')
```
returns an empty address.
I tried symbol `R_BaseSymbol`, and I see the two versions returning the same result.

**Comment by Non-Contradiction** [comment] 2018-03-24 16:01
I wrote a semi-automatic script to do a thoroughly test of all the symbols in [`RCall.Const`](https://github.com/JuliaInterop/RCall.jl/blob/master/src/Const.jl). And most of the symbols return the same results of the `libR` and no-`libR` version **except** the followings which `libR` returns empty addresses but no-`libR` returns non-empty addresses:
```
NaString
MissingArg
NameSymbol
NamesSymbol
EmptyEnv
GlobalEnv
BaseEnv
BaseNamespace
NilValue
UnboundValue
```

**Comment by randy3k** [comment] 2018-03-24 16:18
It looks like `cglobal(:R_BaseNamespace, Ptr{RCall.UnknownSxp}))` is not the correct address neither.

The following works on rstudio@mac, but not rstudio@ubuntu
```
JuliaCall:::juliacall_cmd('ptr  = unsafe_load(cglobal(:R_BaseNamespace, Ptr{RCall.UnknownSxp}))')
JuliaCall:::juliacall_cmd('println(RObject(ptr))')
```

**Comment by randy3k** [comment] 2018-03-24 17:55
[This](https://github.com/JuliaInterop/RCall.jl/commit/ff8f8e8cb3773987f0efa1003b6184a93b7a41f0) should fix the issue. The idea is to use `cglobal(:object, Ptr{Void})` for embedded R.

**Comment by Non-Contradiction** [comment] 2018-03-24 18:21
@randy3k Thanks very much. With the new master of `RCall`, `julia_setup()` is fine and the basic functionality of `JuliaCall` works without problem on RStudio+ubuntu. And everything is also okay on my mac as far as I can tell.
@dmbates Could you confirm this? The master of `RCall` should enable `JuliaCall` to work in RStudio+ubuntu.

**Comment by randy3k** [comment] 2018-03-24 18:59
It turns out that `cglobal(:object, Ptr{Void})` doesn't work on macOS, so I am now using a try and catch block to load the constants.

**Closed** 2018-03-30 16:10 UTC
