### ISSUE TITLE
ERROR: LoadError: syntax: Global method definition around C:\Users\PC

### ISSUE THREAD

**Issue by Faraz564** [Non-Contradiction/JuliaCall#203] opened 2023-07-01 10:25 UTC
Hi I am updating julia path in terminal. As Julia_Setup is not working in my system.  
I follow the following setup.
ENV["R_HOME"]="C:/Environment/R-4.3.1"
"C:/Environment/R-4.3.1"
**But the following syntax creat error. Please write suggestion for this error**
Base.include(Main,"C:/Users/PC/AppData/Local/R/win-library/4.3/JuliaCall/julia/setup.jl")
ERROR: LoadError: syntax: Global method definition around C:\Users\PC\AppData\Local\R\win-library\4.3\JuliaCall\julia\JuliaObject.jl:77 needs to be placed at the top level, or use "eval".
Stacktrace:
 [1] top-level scope
   @ C:\Users\PC\AppData\Local\R\win-library\4.3\JuliaCall\julia\JuliaObject.jl:75
 [2] include(mod::Module, _path::String)
   @ Base .\Base.jl:457
 [3] include(x::String)
   @ Main.JuliaCall C:\Users\PC\AppData\Local\R\win-library\4.3\JuliaCall\julia\setup.jl:16
 [4] top-level scope
   @ C:\Users\PC\AppData\Local\R\win-library\4.3\JuliaCall\julia\setup.jl:99
 [5] include(mod::Module, _path::String)
   @ Base .\Base.jl:457
 [6] top-level scope
   @ REPL[7]:1
in expression starting at C:\Users\PC\AppData\Local\R\win-library\4.3\JuliaCall\julia\JuliaObject.jl:75
in expression starting at C:\Users\PC\AppData\Local\R\win-library\4.3\JuliaCall\julia\setup.jl:16

julia> "C:/Environment/R-4.3.1";Base.include(Main,"C:/Users/PC/AppData/Local/R/win-library/4.3/JuliaCall/julia/setup.jl")ulia/setup.jl")
WARNING: replacing module JuliaCall.                                                                                    liaObject.jl:77 needs to be placed at the top level, or use "ev
ERROR: LoadError: syntax: Global method definition around C:\Users\PC\AppData\Local\R\win-library\4.3\JuliaCall\julia\JuaCall\julia\JuliaObject.jl:77 needs to be placed at the top level, or use "eval".
Stacktrace:
 [1] top-level scope
   @ C:\Users\PC\AppData\Local\R\win-library\4.3\JuliaCall\julia\JuliaObject.jl:75
 [2] include(mod::Module, _path::String)
   @ Base .\Base.jl:457
 [3] include(x::String)
   @ Main.JuliaCall C:\Users\PC\AppData\Local\R\win-library\4.3\JuliaCall\julia\setup.jl:16
 [4] top-level scope
   @ C:\Users\PC\AppData\Local\R\win-library\4.3\JuliaCall\julia\setup.jl:99
 [5] include(mod::Module, _path::String)
   @ Base .\Base.jl:457
 [6] top-level scope
   @ REPL[8]:1
in expression starting at C:\Users\PC\AppData\Local\R\win-library\4.3\JuliaCall\julia\JuliaObject.jl:75
in expression starting at C:\Users\PC\AppData\Local\R\win-library\4.3\JuliaCall\julia\setup.jl:16

**Comment by Non-Contradiction** [comment] 2023-07-13 16:33
Thank you very much for the feedback! The problem is due to an upgrade in some dependency of JuliaCall and should be fixed by #199 and the fix is already merged into master of JuliaCall. 
Before the new version of JuliaCall is on CRAN, you can try the fix by using devtools to install the master version of JuliaCall.
If there is still any problem for the fix, pls feel free to reopen the issue.

**Closed by Non-Contradiction** 2023-07-13 16:33 UTC
