### ISSUE TITLE
need to check if `RCall` is precompiled with the current R.

### ISSUE THREAD

**Issue by randy3k** [Non-Contradiction/JuliaCall#9] opened 2017-09-27 19:26 UTC
You might need to check if `RCall.Rhome` is the same as `Sys.getenv("R_HOME")` when using RCall. Otherwise, the call to `julia_setup()` will freeze indefinitely.

**Comment by Non-Contradiction** [comment] 2017-09-27 19:38
In `julia_setup()`, I did something like `.julia$cmd(paste0('ENV["R_HOME"] = "', R.home(), '"'))`. So the R which RCall uses should be the same as the R which loads JuliaCall library, isn't it?

**Comment by randy3k** [comment] 2017-09-27 19:41
No, RCall is precompiled with an R distribution found when RCall is installed. You would need to execute `Base.compilecache("RCall")` if R has been updated. See http://juliainterop.github.io/RCall.jl/stable/installation.html#Updating-R-1

**Comment by Non-Contradiction** [comment] 2017-09-27 19:48
Thank you very much for pointing this out. Previously, during the `julia_setup()`, there is `Base.compilecache("RCall")`, but removed later. We do need to check this.

**Comment by randy3k** [comment] 2017-09-27 20:04
No problem. However, it may be tricky to check the `RCall.Rhome` without loading `RCall`. One possibility is to do `system2("julia", "-e 'using RCall; println(RCall.Rhome);'", stdout = TRUE)`, but it may check an extra one/two seconds to load.

Another possibility is for RCall to write a file `~/.julia/v0.6/RCall/deps/R` with content of `R_HOME`, similar to what `PyCall` is doing (`PyCall` has a file `~/.julia/v0.6/PyCall/deps/PYTHON`)

**Comment by Non-Contradiction** [comment] 2017-09-27 20:06
One more question, when I `Base.compilecache("RCall")`, how do I tell RCall to precompile against the R I'm using?

**Comment by randy3k** [comment] 2017-09-27 20:09
Since JuliaCall is run inside an R environment with the variable `R_HOME`. `RCall` will pick up the current R when it is recompiled.

PS: i actually don't know if it is still possible to run `using RCall; RCall.Rhome` if RCall was precompiled with current R.

**Comment by Non-Contradiction** [comment] 2017-09-27 20:15
Due to an issue in julia in version 0.6.0, it is not possible to use things like `Base.compilecache` in embedding julia, but the issue is already fixed in some commits, so I guess in future this should be okay. Since the `Base.compilecache` is not possible to run inside the R environment now, how to tell RCall to pick up the R version that is needed?

**Comment by randy3k** [comment] 2017-09-27 20:18
There is no way do it except asking user to open julia and do

julie -e 'ENV["R_HOME"] = "<path to R>"; Base.compilecache("RCall");'

**Comment by randy3k** [comment] 2017-09-27 20:21
You could test if `system2("julia", "-e 'using RCall; println(RCall.Rhome);'", stdout = TRUE)` is the same as `R.home()`. If not, run `system2("julie", "-e 'ENV[\"R_HOME\"] = \"<path to R>\"; Base.compilecache(\"RCall\");'")`

**Comment by Non-Contradiction** [comment] 2017-10-02 15:31
@randy3k Does this file deal with the problem here correctly? 
<https://github.com/Non-Contradiction/JuliaCall/blob/master/inst/julia/RCallprepare.jl>

**Comment by randy3k** [comment] 2017-10-02 15:36
Though I am not sure if julia needs to restart after `Base.compilecache`

**Comment by Non-Contradiction** [comment] 2017-10-02 15:39
Currently, the `Base.compilecache` is done before the init of embedding julia. And embedding julia will load `RCall` again. So there should be no problem?

**Comment by Non-Contradiction** [comment] 2017-10-10 18:51
I just tested whether the issue has been solved on appveyor.
And the issue seems solved:
<https://ci.appveyor.com/project/Non-Contradiction/tests/build/1.0.3>
Install julia 0.6 and R 3.4.2 (R1) and R 3.3.3 (R2) and install `JuliaCall` from github for both R versions.

And JuliaCall works in both of the cases. And `RCall.Rhome` is set correctly.

    C:\projects\R1\bin\x64\Rscript -e "JuliaCall::julia_eval(\"RCall.Rhome\")"
    Julia at location C:\projects\julia\bin will be used.
    Julia version 0.6.0 found.
    Julia initiation...
    Finish Julia initiation.
    Loading setup script for JuliaCall...
    Finish loading setup script for JuliaCall.
    [1] "C:/projects/R1"
    Julia exit.

    C:\projects\R2\bin\x64\Rscript -e "JuliaCall::julia_eval(\"RCall.Rhome\")"
    Julia at location C:\projects\julia\bin will be used.
    Julia version 0.6.0 found.
    Julia initiation...
    Finish Julia initiation.
    Loading setup script for JuliaCall...
    Finish loading setup script for JuliaCall.
    [1] "C:/projects/R2"
    Julia exit.

**Closed by Non-Contradiction** 2017-10-10 18:51 UTC
